Develop
VinokurovAlexander/junior-course-boilerplate pull request #3
Opened 2020-04-06 10:59 UTC by VinokurovAlexander

2020-04-06 14:58 UTC, CSSSR-School requested changes

2020-04-06 14:58 UTC, CSSSR-School commented on src/components/ProductsList/ProductsList.js
> +    return this.props.products.slice(0, PRODUCTS_NUMBER)
Думаю на этом этапе `slice` уже лишний. Всё равно ведь и так все товары выводишь.

2020-04-06 14:58 UTC, CSSSR-School commented on src/components/ProductsList/ProductsList.js
> +      .filter((product) => (product.price >= this.props.price.min) && (product.price <= this.props.price.max))
`Добавь нормализацию данных — подними стейт на уровень приложения (в корневой элемент), отфильтруй товары.`

Фильтрацию тоже в корневой нужно вынести, сделаем список максимально "тупым", чтобы он только рендерил список. Всё равно на этапе контекста и редакса придём к этому.

2020-04-06 14:58 UTC, CSSSR-School commented on src/components/Form/Form.js
> +        <label>
Инпут есть, а аттрибута `for`  нет.

2020-04-07 18:52 UTC, VinokurovAlexander commented on src/components/Form/Form.js
> +        <label>
А зачем он? input же внутри label

2020-04-08 16:09 UTC, vislogurov approved these changes

2020-04-12 08:24 UTC, merged