Controlled controls and optimization
VinokurovAlexander/junior-course-boilerplate pull request #4
Opened 2020-07-12 16:46 UTC by VinokurovAlexander

2020-07-15 17:01 UTC, d-batmanov requested changes
Обнови пожалуйста проект по репозиторию, от которого делал форк, там добавлены линтеры, которые помогут избежать типичных ошибок. https://github.com/CSSSR-School/junior-course-boilerplate

2020-07-15 17:01 UTC, d-batmanov commented on src/components/discount/discount.js
> +import pt from 'prop-types';
Одинарные или двойные кавычки во всем проекте? Нужно делать единообразно.

2020-07-15 17:01 UTC, d-batmanov commented on src/components/discount/discount.js
> +export default InputDiscount;
Нет пустой строки в конце.

2020-07-15 17:01 UTC, d-batmanov commented on src/components/discount/discount.module.css
> +    font-family: OpenSans, sans-serif;
Шрифт наследуется, от родителя, для body OpenSans уже задан. Нет необходимости прописывать его еще раз

2020-07-15 17:01 UTC, d-batmanov commented on src/components/discount/discount.module.css
> +    font-family: OpenSans, sans-serif;
см. комментарий выше

2020-07-15 17:01 UTC, d-batmanov commented on src/components/form/form.js
> +  handleChange(evt, value) {
Использование стрелочной функции позволит сохранить контекст и не писать лишние строки в конструкторе.

2020-07-15 17:01 UTC, d-batmanov commented on src/components/form/form.js
> +    if (isNewValue) {
Лучше сделать guard expression, если ! isNewValue, то return. а иначе выполняется тело метода. при расширении логики не придется писать основной код метода в if, убирается бесполезная вложенность.

2020-07-15 17:01 UTC, d-batmanov commented on src/components/form/form.js
> +        <label>
Чтобы показать пользователю, что label как то отзывается на взаимодействие, ему лучше задать cursor pointer

2020-07-15 17:01 UTC, d-batmanov commented on src/components/form/form.js
> +import InputDiscount from "../discount/discount";
Компонент импортируется из директории **discount** под именем InputDiscount. Потенциально, вся эта неоднородность может очень сильно запутать.
1. Директория называется также как компонент.
2. Импортируется компонент с тем же названием, с которым он и экспортируется,  если нет явных причин отойти от правила.
3. Директории компонентов принято называть с большой буквы. Примеры: https://github.com/mui-org/material-ui/tree/next/packages/material-ui/src
4. (По желанию) Файл компонента можно именовать как index.js. По имени директории уже понятно что это за компонент. Это позволит писать при импорте "../discount"; вместо "../discount/discount";

2020-07-15 17:01 UTC, d-batmanov commented on src/components/discount/discount.js
> +class InputDiscountUI extends LogRender {
Мне кажется, что заголовок тут лишний, заголовки "Цена" и "Скидка" имеют одинаковые стили, от инпута скидки нужна функциональность. В остальном он такой же инпут, элемент формы, не более того.

2020-07-15 17:01 UTC, d-batmanov commented on src/components/input-number/input-number.js
> +        type='text'
В props для строковых значений используют двойные кавычки

2020-07-15 17:01 UTC, d-batmanov commented on src/components/input-number/input-number.js
> +import styles from "./input.module.css";
Где то импортится styles, где то s. Нужной прийти к единому шаблону.

2020-07-15 17:01 UTC, d-batmanov commented on src/components/discount/discount.js
> +const InputDiscount = WithMask(InputDiscountUI);
Между inputNumber и inputDiscout есть разница, которая заставляет их разделить на два компонента?

2020-07-15 17:01 UTC, d-batmanov commented on src/components/with-mask/with-mask.js
> +const WithMask = (OriginalComponent) => {
Для легкого дебага имеет смысл добавить имя для хока, https://ru.reactjs.org/docs/higher-order-components.html#convention-wrap-the-display-name-for-easy-debugging

2020-07-15 17:01 UTC, d-batmanov commented on src/components/with-mask/with-mask.js
> +            return <OriginalComponent {...this.props} handleChange = {this.handleChange}/>
В handleChange пробелы у знака = лишние

2020-07-15 17:01 UTC, d-batmanov commented on src/index.js
> +      sale: DEFAULT_SALE_SIZE
getMinAndMaxPrice**AndSaleAnd...** :) Думаю, следует назвать метод более абстрактно, чтобы он не вводил в заблуждение

2020-07-16 07:19 UTC, VinokurovAlexander commented on src/components/discount/discount.js
> +export default InputDiscount;
Линтер молчит по этому поводу. Может добавить тогда правило?

2020-07-16 07:21 UTC, VinokurovAlexander commented on src/components/form/form.js
> +  handleChange(evt, value) {
Это нормальная практика? Вроде как не рекомендуется https://ru.reactjs.org/docs/faq-functions.html#arrow-function-in-render

2020-07-17 05:50 UTC, VinokurovAlexander commented on src/components/form/form.js
> +  handleChange(evt, value) {
@d-batmanov

2020-07-17 07:22 UTC, d-batmanov commented on src/components/form/form.js
> +  handleChange(evt, value) {
Не рекомендуется использовать стрелочные функции внутри render() метода, т.к. он вызывается всегда, когда в компоненте или родителе происходят изменения, функция, переданная в onClick как onClick={() => myCode} будет создаваться заново, старая функция не будет равна новой, соответственно реакт будет думать, что переданный onClick изменился и компонент будет перерендерен еще раз. 
Создавать стрелочные функции в теле класса можно, это не вызовет проблем перерендера. Вообще, чаще всего методы класса всегда делают стрелочными функциями, чтобы не терять контекст, все методы смотрятся единообразно, минусов в подходе нет, т.к. this внутри функции в 99% случаев должен принадлежать классу, если этот 1 процент и возникнет, то с большей долей вероятности что то делается не так.

2020-07-17 07:25 UTC, d-batmanov requested changes

2020-07-17 07:25 UTC, d-batmanov commented on src/components/Input/index.js
> +                    className={styles.input}
поехали отступы

2020-07-17 07:25 UTC, d-batmanov commented on src/components/WithNumberMask/index.js
> +  return WrappedComponent.displayName || WrappedComponent.name || 'Component';
2 пробела или 4 ?

2020-07-17 16:11 UTC, d-batmanov approved these changes
Мелкие правки, повторное ревью не требуется

2020-07-17 16:11 UTC, d-batmanov commented on src/components/Input/index.js
> +export default Input;
export default WithNumberMask(InputUI);
Можно так.

2020-07-19 15:57 UTC, merged