Redux
VinokurovAlexander/junior-course-boilerplate pull request #6
Opened 2020-10-05 08:14 UTC by VinokurovAlexander

2020-10-08 19:57 UTC, CSSSR-School requested changes

2020-10-08 19:57 UTC, CSSSR-School commented on README.md
> +В папке `src` лежит react код который собирается и неявно подключается к странице - его не надо явно подключать. Входной точкой является файл `src/store.js` и в нем должно быть размещена инициализаци
Давай оставим адрес входной точки таким же, каким он и был - index.js является общепринятой практикой и будет не совсем правильно при каждом изменении используемых технологий править названия файлов.

2020-10-08 19:57 UTC, CSSSR-School commented on README.md
> +В продакшн режиме приложение оптимизировано для производительности, но при этом его код минифицирован и его сложнее отлаживать и разрабатывать.
Хороший совет - лучше всего вносить в пулл-реквест именно те изменения, которые напрямую относятся к задаче. Может так оказаться, что пулл-реквест будет отклонен, или даже принят и отменен, а вместе с этим и все полезные улучшательства тоже будут утеряны.

2020-10-08 19:57 UTC, CSSSR-School commented on src/components/Form/index.js
> +  resetBtnClickHandler = e => {
Тут для события используется `e`, а выше - `evt`. Оптимальнее всего поддерживать консистентность нейминга на протяжении всего проекта. Используй полные слова (event, error) - не ошибешься.

2020-10-08 19:57 UTC, CSSSR-School commented on src/components/Form/index.js
> +    const props = this.props;
Давай деструктурируем пропсы и сэкономим еще больше знаков. Вот так:
```
const { priceMin, priceMax } = this.props
```

2020-10-08 19:57 UTC, CSSSR-School commented on src/components/Form/index.js
> +          <button onClick={this.resetBtnClickHandler}>Сбросить фильтры</button>
Давай назовем по тому же подобию что и выше - handleResetButtonClick. Признак хорошего тона - указать аттрибут type у кнопки.

2020-10-08 19:57 UTC, CSSSR-School commented on src/containers/app.js
> +    resetFilters: () => dispatch({ type: 'RESET_FILTER' })
Давай обезопасим себя от опечаток и выведем все типы в отдельные переменные, которые и будем передавать в dispatch:
```
const UPDATE_CHECKED_CATEGORIES = 'UPDATE_CHECKED_CATEGORIES'
...
dispatch({ type: UPDATE_CHECKED_CATEGORIES })
```

2020-10-08 19:57 UTC, CSSSR-School commented on src/containers/app.js
> +import { connect }  from 'react-redux';
контейнер - это такой же компонент, давай оформим каждый контейнер в отдельную папку.

2020-10-08 19:57 UTC, CSSSR-School commented on src/containers/list.js
> +const getFilteredProducts = (price, checkedCategories, products) => {
Можно прямо в аргументах назвать цену как currentPrice.

2020-10-08 19:57 UTC, CSSSR-School commented on src/containers/list.js
> +  const isMoreThanMinPrice = product => product.price >= currentPrice.min;
Все эти функции можно вынести за пределы текущей, чтобы они заново не создавались в момент её вызова.

2020-10-08 19:57 UTC, CSSSR-School commented on src/containers/list.js
> +  const setFilter = product =>
Эта функция ведь задумана тоже возвращать булево? Давай тогда так же назовем её с использованием is в начале.

2020-10-08 19:57 UTC, CSSSR-School commented on src/containers/list.js
> +  return products.filter((product) => setFilter(product))
В такой ситуации можно просто передать в filter ссылку на фукнцию:
```
products.filter(setFilter)
```

2020-10-08 19:57 UTC, CSSSR-School commented on src/containers/list.js
> +    allProducts: state.products,
В таких ситуациях можно делать деструктуризацию и использовать сокращенный синтаксис для объектов:
```
const mapStateToProps = ({ price }) => ({
    price,
})
```

2020-10-08 19:57 UTC, CSSSR-School commented on src/reducer.js
> +      const changedCategory = action.payload.changedCategory;
Давай сразу деструктурируем action, чтобы получить прямой доступ к payload.

2020-10-08 19:57 UTC, CSSSR-School commented on src/containers/app.js
> +import { default as AppUI } from '../components/App';
При использовании дефолтного экспорта достаточно сделать:
```
import AppUI from '../components/App';
```

2020-10-09 06:29 UTC, VinokurovAlexander commented on README.md
> +В продакшн режиме приложение оптимизировано для производительности, но при этом его код минифицирован и его сложнее отлаживать и разрабатывать.
Ясно, спасибо. Но я, кстати, не понял почему этот файл вообще был изменён. Сам я его не трогал.

2020-10-09 06:46 UTC, VinokurovAlexander commented on src/components/Form/index.js
> +          <button onClick={this.resetBtnClickHandler}>Сбросить фильтры</button>
Теперь понятно почему мне пришлось делать eventDefault(), у кнопки по умолчанию type submit.

2020-10-09 08:07 UTC, VinokurovAlexander commented on README.md
> +В папке `src` лежит react код который собирается и неявно подключается к странице - его не надо явно подключать. Входной точкой является файл `src/store.js` и в нем должно быть размещена инициализаци
Это видимо так сработал рефакторинг в IDE после изменения имени файла

2020-10-09 19:26 UTC, CSSSR-School commented on src/components/Form/index.js
> +          <button onClick={this.resetBtnClickHandler}>Сбросить фильтры</button>
@VinokurovAlexander на всякий случай - у кнопки по умолчанию type submit именно в том случае, если она находится внутри формы. Доступность - это отдельная тема, которая выходит за рамки нашего курса, но стоит брать её во внимание.

2020-10-10 06:47 UTC, VinokurovAlexander commented on src/components/Form/index.js
> +          <button onClick={this.resetBtnClickHandler}>Сбросить фильтры</button>
@CSSSR-School понял, спасибо

2020-10-10 19:51 UTC, CSSSR-School approved these changes

2020-10-10 19:51 UTC, CSSSR-School commented on src/reducer.js
> +export const reducer = (state = initialState, action) => {
`export const reducer = (state = initialState, { type, payload }) => {...}` - и ниже будет еще меньше кода. Мы внутри редюсера - в любом случае, будущим коллегам будет понятно, о каких type и payload идет речь.

2020-10-13 05:23 UTC, merged