Выполнил задание Redux Modularization
VinokurovAlexander/junior-course-boilerplate pull request #7
Opened 2021-03-10 15:02 UTC by VinokurovAlexander

2021-03-12 07:50 UTC, vislogurov requested changes

2021-03-12 07:50 UTC, vislogurov commented on src/components/Link/index.js
> +    if (isDisabled) {
disabled можно повесить на саму кнопку, затем добавить pointer-events: none и тогда событие вообще не пройдёт. И не нужна будет проверка.

2021-03-12 17:17 UTC, VinokurovAlexander commented on src/components/Link/index.js
> +    if (isDisabled) {
Сейчас это ссылка, видимо нужно переделать на кнопку? В таком случае зачем тогда `pointer-events: none`? Атрибута disabled не достаточно?

2021-03-12 17:20 UTC, vislogurov commented on src/components/Link/index.js
> +    if (isDisabled) {
pointer-events none нужен чтобы событие вообще не возникло на элементе

2021-03-13 05:53 UTC, vislogurov approved these changes

2021-03-19 07:05 UTC, merged