Выполнил задание Роутинг
VinokurovAlexander/junior-course-boilerplate pull request #8
Opened 2021-03-21 12:30 UTC by VinokurovAlexander

2021-03-24 10:10 UTC, kuflash requested changes
Привет! Есть некоторые недочеты

2021-03-24 10:10 UTC, kuflash commented on src/components/App/index.js
> +    <Route path={'/id=:number(\\d+)'} component={ProductPage} />
Такой формат пути хоть и работает, но он не совсем корректный с точки зрения общих подходов. Обычно формат `key=value` используется в query string, т.е. после указания знака вопроса. Пример:
```
/some-path?id=1
```

Обычно это применяется на каких-то страницах коллекций. В твоем случае это страница списка товаров

А когда мы переходим на страницу конкретного товара, то пути обычно выглядит таким образом:
```
/products/1
/products/2
/products/3
...
```

Попробуй применить именно такой подход

2021-03-24 10:10 UTC, kuflash commented on src/components/Link/index.js
> +  const url = `?${queryString.stringify({...parsedQuery, page: index}, { skipEmptyString: true, arrayFormat: 'comma' })}`;
Не очень хорошо, когда у тебя компонент ссылки знает о том, какие `query` параметры могут быть. В большом проекте этих параметров может быть очень большое количество. И тогда при каждом добавлении нового параметра придется его изменять.

Попробуй сделать так, чтобы компонент просто принимал пропс `url`, и прокидывал его в соответствующий компонент `Link`.

Если пойти еще дальше, глядя на текущий компонент `LinkUI`, то по сути он занимается стилизацией ссылки. Поэтому, можно сделать стилизованный компонент, без лишних оберток. Плюс такого подхода - у тебя компонент будет принимать все необходимые тебе кастомные пропсы (`isBig`, `isActive` и т.п), а также пропсы самого компонента `Link` из `react-router`.

Вот можно тут посмотреть пример [METHOD 2](https://dev.to/ridhikgovind/how-to-style-your-react-router-links-using-styled-components-2350)

2021-03-24 10:10 UTC, kuflash commented on src/components/BackLink/index.js
> +    <Component onClick={handleClick}>
Вот тут есть недочет. У тебя `Component` является html элементом `div`. И на него вешается обработчик `click`. Это работает, но так делать не стоит, так как это не интерактивный элемент. В твоем случае это должен быть `button`.

Бывают конечно случаи, когда на `div` и подобных ему элементах надо обрабатывать клики, но тогда стараются сделать этот элемент более похожим на интерактивный, используя aria-атрибуты и реализуя все возможные состояния интерактивного элемента.

2021-03-25 06:05 UTC, VinokurovAlexander commented on src/components/Link/index.js
> +  const url = `?${queryString.stringify({...parsedQuery, page: index}, { skipEmptyString: true, arrayFormat: 'comma' })}`;
Правильно ли я понял, что логика формирования `url` корректная, её просто нужно вынести из компонента на уровень "повыше" ?

2021-03-25 08:36 UTC, kuflash commented on src/components/Link/index.js
> +  const url = `?${queryString.stringify({...parsedQuery, page: index}, { skipEmptyString: true, arrayFormat: 'comma' })}`;
Да, формирование `url` можно оставить таким же

2021-03-26 19:04 UTC, kuflash commented
Теперь все хорошо :) Можешь вливать в `master`

2021-03-27 06:27 UTC, merged